{% set name = "ensmallen" %}
{% set version = "1.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mlpack/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 7d9c72fb90b2f3a9965a6c6952d976ddf79c7e44e84d4cd7a68a56e108013944

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]

  host:
    - armadillo >=6.500.0
    - libblas
    - libcblas
    - openmp

  run:
    - armadillo
    - openmp

test:
  commands:
    - test -f $PREFIX/include/ensmallen.hpp                    # [unix]
    - test -d $PREFIX/include/ensmallen_bits                   # [unix]
    - if not exist %LIBRARY_INC%\\ensmallen.hpp exit 1         # [win]
    - if not exist %LIBRARY_INC%\\ensmallen_bits exit 1        # [win]
    
about:
  home: http://ensmallen.org/
  license: BSD-3
  license_family: BSD
  license_file: COPYRIGHT.txt
  summary: 'ensmallen is a C++ header-only library for mathematical optimization.'
  description: |
    ensmallen provides a simple set of abstractions for writing an objective 
    function to optimize. It     also provides a large set of standard and 
    cutting-edge optimizers that can be used for virtually any mathematical 
    optimization task. These include full-batch gradient descent techniques, 
    small-batch techniques, gradient-free optimizers, and constrained optimization.
  doc_url: http://ensmallen.org/docs.html
  dev_url: https://github.com/mlpack/ensmallen

extra:
  recipe-maintainers:
    - marcelotrevisani
